# Form implementation generated from reading ui file 'UserGuide.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserGuide(object):
    def setupUi(self, UserGuide):
        UserGuide.setObjectName("UserGuide")
        UserGuide.resize(508, 312)
        self.centralwidget = QtWidgets.QWidget(parent=UserGuide)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 501, 281))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.frame)
        UserGuide.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=UserGuide)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 26))
        self.menubar.setObjectName("menubar")
        UserGuide.setMenuBar(self.menubar)

        self.retranslateUi(UserGuide)
        QtCore.QMetaObject.connectSlotsByName(UserGuide)

    def retranslateUi(self, UserGuide):
        _translate = QtCore.QCoreApplication.translate
        UserGuide.setWindowTitle(_translate("UserGuide", "User Guide"))
        self.textBrowser.setHtml(_translate("UserGuide", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.6pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:6px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">MetaBioDetect User Guide</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MetaBioDetect provides a graphical workflow for DNA metabarcoding and amplicon sequence analysis. This guide describes the main steps of the pipeline and the purpose of the available parameters.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">1. Input Data</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Load your raw sequencing files into the software. MetaBioDetect supports workflows using paired-end reads (forward and reverse) as well as single-end reads, depending on the selected analysis step.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">2. Adapter and Primer Trimming</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Adapter and primer trimming is performed using </span><span style=\" font-size:9pt; font-weight:600;\">Cutadapt</span><span style=\" font-size:9pt;\">. This step removes adapter or primer sequences from raw reads before downstream analysis.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Available parameters:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Overlap</span> – Minimum overlap required between the read and adapter/primer sequence.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Error rate</span> – Maximum allowed mismatch rate during trimming.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Discard untrimmed reads</span> – Remove reads where the expected adapter/primer is not found.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Minimum length</span> – Remove reads shorter than the selected threshold after trimming.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Quality cutoff</span> – Trim or remove low-quality bases/reads.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Max-N</span> – Limit the number of ambiguous bases allowed in a read.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Other command</span> – Add additional Cutadapt options if required.</li></ul>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">3. Merging Reads</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">If paired-end data are provided, forward and reverse reads can be merged into a single sequence. This step combines overlapping read pairs to reconstruct the full amplicon sequence.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Available parameters:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Minimum overlap</span> – Minimum overlap length required for merging.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Maximum overlap</span> – Maximum allowed overlap length.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Overlap identity</span> – Minimum sequence identity required in the overlap region.</li></ul>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">4. Length Filtering</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Length filtering removes reads outside the expected amplicon size range. This improves data quality by excluding unusually short or long sequences.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Available parameters:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Minimum length</span> – Keep only reads above the selected length.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Maximum length</span> – Keep only reads below the selected length.</li></ul>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">5. Dereplication</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Dereplication identifies unique sequences and collapses identical reads into a single representative sequence with abundance information. This reduces redundancy and speeds up downstream analysis.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">6. Denoising / Clustering</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MetaBioDetect can process sequence reads into biologically meaningful units such as</span><span style=\" font-size:9pt; font-weight:600;\"> ASVs</span><span style=\" font-size:9pt;\"> or </span><span style=\" font-size:9pt; font-weight:600;\">OTUs</span><span style=\" font-size:9pt;\">, depending on the selected workflow.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Denoising methods such as </span><span style=\" font-size:9pt; font-weight:600;\">UNOISE</span><span style=\" font-size:9pt;\"> can be used to remove sequencing errors and recover high-confidence biological sequence variants. Clustering can also be applied to group similar reads into OTUs based on sequence similarity thresholds.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">7. Chimera Detection</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Chimeric sequences generated during PCR amplification can be identified and removed before taxonomy assignment. This step helps reduce false-positive biological results.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">8. Taxonomic Identification</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Taxonomic assignment can be performed using </span><span style=\" font-size:9pt; font-weight:600;\">BLAST</span><span style=\" font-size:9pt;\"> against online databases, local reference databases, or custom user-provided databases.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Available parameters:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Percentage identity</span> – Minimum identity threshold for accepted hits.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Max target sequences</span> – Maximum number of BLAST matches returned per query.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">CPU threads</span> – Number of processor threads used during analysis.</li></ul>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">9. Sequential or Stepwise Workflow</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The software can be used in two ways:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Sequential workflow</span> – Run the analysis from raw input data to final output in one pipeline.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Stepwise workflow</span> – Run each step independently, inspect intermediate files and logs, and continue later if needed.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The stepwise option is useful for troubleshooting, checking intermediate outputs, or resuming an interrupted analysis.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">10. Logs and Intermediate Files</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">For each analysis step, MetaBioDetect stores log files and intermediate outputs. These files help users verify parameter settings, monitor processing progress, and review results before continuing to the next step.</span></p>\n"
"<p style=\" margin-top:10px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">11. General Notes</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use appropriate trimming and filtering parameters based on the quality of your sequencing data.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Always review intermediate results before final taxonomic interpretation.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When using custom databases, ensure that the reference sequences are properly formatted.</li>\n"
"<li style=\" font-size:9pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default settings may be suitable for many datasets, but advanced users can adjust parameters for specific projects.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Output:</span><span style=\" font-size:9pt;\"><br />MetaBioDetect generates processed sequence files, intermediate analysis outputs, log files, and taxonomic identification results that can be used for downstream ecological or biodiversity studies.</span></p></body></html>"))