from PyQt6 import QtCore, QtGui, QtWidgets
import os



BASE_DIR = os.path.dirname(os.path.abspath(__file__))


class Ui_AllinOne(object):
    def setupUi(self, AllinOne):
        AllinOne.setObjectName("AllinOne")
        AllinOne.resize(938, 613)
        self.centralwidget = QtWidgets.QWidget(parent=AllinOne)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(11, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 869, 506))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.scrollAreaWidgetContents_4)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_adapter_trimmig = QtWidgets.QWidget()
        self.tab_adapter_trimmig.setObjectName("tab_adapter_trimmig")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_adapter_trimmig)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_adapter = QtWidgets.QFrame(parent=self.tab_adapter_trimmig)
        self.frame_adapter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_adapter.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_adapter.setObjectName("frame_adapter")
        self.formLayout = QtWidgets.QFormLayout(self.frame_adapter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.label_forward = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_forward.setFont(font)
        self.label_forward.setMouseTracking(True)
        self.label_forward.setWhatsThis("")
        self.label_forward.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_forward.setObjectName("label_forward")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_forward)
        self.lineEdit_forward_trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_forward_trim_adapter.setAutoFillBackground(False)
        self.lineEdit_forward_trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_forward_trim_adapter.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_forward_trim_adapter.setClearButtonEnabled(False)
        self.lineEdit_forward_trim_adapter.setObjectName("lineEdit_forward_trim_adapter")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_forward_trim_adapter)
        self.label_reverse = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_reverse.setFont(font)
        self.label_reverse.setMouseTracking(True)
        self.label_reverse.setWhatsThis("")
        self.label_reverse.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_reverse.setObjectName("label_reverse")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_reverse)
        self.lineEdit_reverse_trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_reverse_trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_reverse_trim_adapter.setObjectName("lineEdit_reverse_trim_adapter")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_reverse_trim_adapter)
        self.label_min = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_min.setFont(font)
        self.label_min.setMouseTracking(True)
        self.label_min.setWhatsThis("")
        self.label_min.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_min.setObjectName("label_min")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_min)
        self.lineEdit_min__trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_min__trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_min__trim_adapter.setObjectName("lineEdit_min__trim_adapter")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_min__trim_adapter)
        self.label_quality = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_quality.setFont(font)
        self.label_quality.setMouseTracking(True)
        self.label_quality.setWhatsThis("")
        self.label_quality.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_quality.setObjectName("label_quality")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_quality)
        self.lineEdit_quality_trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_quality_trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_quality_trim_adapter.setObjectName("lineEdit_quality_trim_adapter")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_quality_trim_adapter)
        self.label_max = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_max.setFont(font)
        self.label_max.setMouseTracking(True)
        self.label_max.setWhatsThis("")
        self.label_max.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_max.setObjectName("label_max")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_max)
        self.lineEdit_max_trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_max_trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_max_trim_adapter.setObjectName("lineEdit_max_trim_adapter")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_max_trim_adapter)
        self.label_overlap = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_overlap.setFont(font)
        self.label_overlap.setMouseTracking(True)
        self.label_overlap.setWhatsThis("")
        self.label_overlap.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_overlap.setObjectName("label_overlap")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_overlap)
        self.lineEdit_overlap_trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_overlap_trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_overlap_trim_adapter.setText("")
        self.lineEdit_overlap_trim_adapter.setObjectName("lineEdit_overlap_trim_adapter")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_overlap_trim_adapter)
        self.label_errorRate = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_errorRate.setFont(font)
        self.label_errorRate.setMouseTracking(True)
        self.label_errorRate.setWhatsThis("")
        self.label_errorRate.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_errorRate.setObjectName("label_errorRate")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_errorRate)
        self.lineEdit_error_trim_adapter = QtWidgets.QLineEdit(parent=self.frame_adapter)
        self.lineEdit_error_trim_adapter.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_error_trim_adapter.setText("")
        self.lineEdit_error_trim_adapter.setObjectName("lineEdit_error_trim_adapter")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_error_trim_adapter)
        self.label_discarduntrim = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_discarduntrim.setFont(font)
        self.label_discarduntrim.setObjectName("label_discarduntrim")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_discarduntrim)
        self.radioButton_yes_trim_adapter = QtWidgets.QRadioButton(parent=self.frame_adapter)
        self.radioButton_yes_trim_adapter.setObjectName("radioButton_yes_trim_adapter")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButton_yes_trim_adapter)
        self.radioButton_no_trim_adapter = QtWidgets.QRadioButton(parent=self.frame_adapter)
        self.radioButton_no_trim_adapter.setChecked(True)
        self.radioButton_no_trim_adapter.setObjectName("radioButton_no_trim_adapter")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButton_no_trim_adapter)
        self.label_othercommand = QtWidgets.QLabel(parent=self.frame_adapter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_othercommand.setFont(font)
        self.label_othercommand.setMouseTracking(True)
        self.label_othercommand.setWhatsThis("")
        self.label_othercommand.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_othercommand.setObjectName("label_othercommand")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_othercommand)
        self.textEdit_othercommand_trim_adapter = QtWidgets.QTextEdit(parent=self.frame_adapter)
        self.textEdit_othercommand_trim_adapter.setObjectName("textEdit_othercommand_trim_adapter")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_othercommand_trim_adapter)
        self.verticalLayout_2.addWidget(self.frame_adapter)
        self.tabWidget.addTab(self.tab_adapter_trimmig, "")
        self.tab_primer_trimming = QtWidgets.QWidget()
        self.tab_primer_trimming.setObjectName("tab_primer_trimming")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_primer_trimming)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_primer = QtWidgets.QFrame(parent=self.tab_primer_trimming)
        self.frame_primer.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_primer.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_primer.setObjectName("frame_primer")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_primer)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(8)
        self.formLayout_2.setVerticalSpacing(4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_forward_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_forward_2.setFont(font)
        self.label_forward_2.setMouseTracking(True)
        self.label_forward_2.setWhatsThis("")
        self.label_forward_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_forward_2.setObjectName("label_forward_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_forward_2)
        self.lineEdit_forward_trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_forward_trim_primer.setAutoFillBackground(False)
        self.lineEdit_forward_trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_forward_trim_primer.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_forward_trim_primer.setClearButtonEnabled(False)
        self.lineEdit_forward_trim_primer.setObjectName("lineEdit_forward_trim_primer")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_forward_trim_primer)
        self.label_reverse_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_reverse_2.setFont(font)
        self.label_reverse_2.setMouseTracking(True)
        self.label_reverse_2.setWhatsThis("")
        self.label_reverse_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_reverse_2.setObjectName("label_reverse_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_reverse_2)
        self.lineEdit_reverse_trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_reverse_trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_reverse_trim_primer.setObjectName("lineEdit_reverse_trim_primer")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_reverse_trim_primer)
        self.label_min_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_min_2.setFont(font)
        self.label_min_2.setMouseTracking(True)
        self.label_min_2.setWhatsThis("")
        self.label_min_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_min_2.setObjectName("label_min_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_min_2)
        self.lineEdit_min__trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_min__trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_min__trim_primer.setObjectName("lineEdit_min__trim_primer")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_min__trim_primer)
        self.label_quality_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_quality_2.setFont(font)
        self.label_quality_2.setMouseTracking(True)
        self.label_quality_2.setWhatsThis("")
        self.label_quality_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_quality_2.setObjectName("label_quality_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_quality_2)
        self.lineEdit_quality_trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_quality_trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_quality_trim_primer.setObjectName("lineEdit_quality_trim_primer")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_quality_trim_primer)
        self.label_max_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_max_2.setFont(font)
        self.label_max_2.setMouseTracking(True)
        self.label_max_2.setWhatsThis("")
        self.label_max_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_max_2.setObjectName("label_max_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_max_2)
        self.lineEdit_max_trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_max_trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_max_trim_primer.setObjectName("lineEdit_max_trim_primer")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_max_trim_primer)
        self.label_overlap_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_overlap_2.setFont(font)
        self.label_overlap_2.setMouseTracking(True)
        self.label_overlap_2.setWhatsThis("")
        self.label_overlap_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_overlap_2.setObjectName("label_overlap_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_overlap_2)
        self.lineEdit_overlap_trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_overlap_trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_overlap_trim_primer.setText("")
        self.lineEdit_overlap_trim_primer.setObjectName("lineEdit_overlap_trim_primer")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_overlap_trim_primer)
        self.label_errorRate_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_errorRate_2.setFont(font)
        self.label_errorRate_2.setMouseTracking(True)
        self.label_errorRate_2.setWhatsThis("")
        self.label_errorRate_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_errorRate_2.setObjectName("label_errorRate_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_errorRate_2)
        self.lineEdit_error_trim_primer = QtWidgets.QLineEdit(parent=self.frame_primer)
        self.lineEdit_error_trim_primer.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_error_trim_primer.setText("")
        self.lineEdit_error_trim_primer.setObjectName("lineEdit_error_trim_primer")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_error_trim_primer)
        self.label_discarduntrim_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_discarduntrim_2.setFont(font)
        self.label_discarduntrim_2.setObjectName("label_discarduntrim_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_discarduntrim_2)
        self.radioButton_yes_trim_primer = QtWidgets.QRadioButton(parent=self.frame_primer)
        self.radioButton_yes_trim_primer.setObjectName("radioButton_yes_trim_primer")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButton_yes_trim_primer)
        self.radioButton_no_trim_primer = QtWidgets.QRadioButton(parent=self.frame_primer)
        self.radioButton_no_trim_primer.setChecked(True)
        self.radioButton_no_trim_primer.setObjectName("radioButton_no_trim_primer")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButton_no_trim_primer)
        self.label_othercommand_2 = QtWidgets.QLabel(parent=self.frame_primer)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_othercommand_2.setFont(font)
        self.label_othercommand_2.setMouseTracking(True)
        self.label_othercommand_2.setWhatsThis("")
        self.label_othercommand_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.label_othercommand_2.setObjectName("label_othercommand_2")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_othercommand_2)
        self.textEdit_othercommand_trim_primer = QtWidgets.QTextEdit(parent=self.frame_primer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_othercommand_trim_primer.sizePolicy().hasHeightForWidth())
        self.textEdit_othercommand_trim_primer.setSizePolicy(sizePolicy)
        self.textEdit_othercommand_trim_primer.setObjectName("textEdit_othercommand_trim_primer")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_othercommand_trim_primer)
        self.verticalLayout_3.addWidget(self.frame_primer)
        self.tabWidget.addTab(self.tab_primer_trimming, "")
        self.tab_merging = QtWidgets.QWidget()
        self.tab_merging.setObjectName("tab_merging")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_merging)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_merging = QtWidgets.QFrame(parent=self.tab_merging)
        self.frame_merging.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_merging.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_merging.setObjectName("frame_merging")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_merging)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setVerticalSpacing(16)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_merging)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_min_overlap_merging = QtWidgets.QLineEdit(parent=self.frame_merging)
        self.lineEdit_min_overlap_merging.setText("")
        self.lineEdit_min_overlap_merging.setObjectName("lineEdit_min_overlap_merging")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_min_overlap_merging)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_merging)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_max_overlap_mismatch_merging = QtWidgets.QLineEdit(parent=self.frame_merging)
        self.lineEdit_max_overlap_mismatch_merging.setText("")
        self.lineEdit_max_overlap_mismatch_merging.setObjectName("lineEdit_max_overlap_mismatch_merging")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_max_overlap_mismatch_merging)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_merging)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.textEdit_other_commands_merging = QtWidgets.QTextEdit(parent=self.frame_merging)
        self.textEdit_other_commands_merging.setObjectName("textEdit_other_commands_merging")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_other_commands_merging)
        self.verticalLayout_4.addWidget(self.frame_merging)
        self.tabWidget.addTab(self.tab_merging, "")
        self.tab_quality_filtering = QtWidgets.QWidget()
        self.tab_quality_filtering.setObjectName("tab_quality_filtering")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_quality_filtering)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(parent=self.tab_quality_filtering)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_10.setObjectName("frame_10")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_11)
        self.label_maxee = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_maxee.setFont(font)
        self.label_maxee.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_maxee.setObjectName("label_maxee")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_maxee)
        self.lineEdit_maxee_quality_filtering = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_maxee_quality_filtering.setObjectName("lineEdit_maxee_quality_filtering")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_maxee_quality_filtering)
        self.label_max_length = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_max_length.setFont(font)
        self.label_max_length.setObjectName("label_max_length")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_max_length)
        self.lineEdit_maxlength_quality_filtering = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_maxlength_quality_filtering.setObjectName("lineEdit_maxlength_quality_filtering")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_maxlength_quality_filtering)
        self.label_min_length = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_min_length.setFont(font)
        self.label_min_length.setObjectName("label_min_length")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_min_length)
        self.lineEdit_minlength_quality_filtering = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_minlength_quality_filtering.setObjectName("lineEdit_minlength_quality_filtering")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_minlength_quality_filtering)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit_max_N_base_quality_filtering = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_max_N_base_quality_filtering.setObjectName("lineEdit_max_N_base_quality_filtering")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_max_N_base_quality_filtering)
        self.label_min_quality_score = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_min_quality_score.setFont(font)
        self.label_min_quality_score.setObjectName("label_min_quality_score")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_min_quality_score)
        self.lineEdit_min_quality_quality_filtering = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_min_quality_quality_filtering.setObjectName("lineEdit_min_quality_quality_filtering")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_min_quality_quality_filtering)
        self.label_relabel = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_relabel.setFont(font)
        self.label_relabel.setObjectName("label_relabel")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_relabel)
        self.lineEdit_relabel_quality_filtering = QtWidgets.QLineEdit(parent=self.frame_10)
        self.lineEdit_relabel_quality_filtering.setObjectName("lineEdit_relabel_quality_filtering")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_relabel_quality_filtering)
        self.label_othercommand_3 = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_othercommand_3.setFont(font)
        self.label_othercommand_3.setObjectName("label_othercommand_3")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_othercommand_3)
        self.textEdit_othercommand_quality_filtering = QtWidgets.QTextEdit(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_othercommand_quality_filtering.sizePolicy().hasHeightForWidth())
        self.textEdit_othercommand_quality_filtering.setSizePolicy(sizePolicy)
        self.textEdit_othercommand_quality_filtering.setObjectName("textEdit_othercommand_quality_filtering")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_othercommand_quality_filtering)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.tabWidget.addTab(self.tab_quality_filtering, "")
        self.tab_identify_unique = QtWidgets.QWidget()
        self.tab_identify_unique.setObjectName("tab_identify_unique")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_identify_unique)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(parent=self.tab_identify_unique)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_12.setObjectName("frame_12")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_12)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setHorizontalSpacing(11)
        self.formLayout_5.setVerticalSpacing(12)
        self.formLayout_5.setObjectName("formLayout_5")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_13)
        self.label_relabel_2 = QtWidgets.QLabel(parent=self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_relabel_2.setFont(font)
        self.label_relabel_2.setObjectName("label_relabel_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_relabel_2)
        self.lineEdit_relabel_seq_identify_unique = QtWidgets.QLineEdit(parent=self.frame_12)
        self.lineEdit_relabel_seq_identify_unique.setObjectName("lineEdit_relabel_seq_identify_unique")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_relabel_seq_identify_unique)
        self.label_othercommand_4 = QtWidgets.QLabel(parent=self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_othercommand_4.setFont(font)
        self.label_othercommand_4.setObjectName("label_othercommand_4")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_othercommand_4)
        self.textEdit_othercommand_identify_unique = QtWidgets.QTextEdit(parent=self.frame_12)
        self.textEdit_othercommand_identify_unique.setObjectName("textEdit_othercommand_identify_unique")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_othercommand_identify_unique)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.tabWidget.addTab(self.tab_identify_unique, "")
        self.tab_clustering = QtWidgets.QWidget()
        self.tab_clustering.setObjectName("tab_clustering")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_clustering)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_clustering = QtWidgets.QFrame(parent=self.tab_clustering)
        self.frame_clustering.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_clustering.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_clustering.setObjectName("frame_clustering")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_clustering)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setVerticalSpacing(12)
        self.formLayout_6.setObjectName("formLayout_6")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_clustering)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_3)
        self.label_othercommand_5 = QtWidgets.QLabel(parent=self.frame_clustering)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_othercommand_5.setFont(font)
        self.label_othercommand_5.setObjectName("label_othercommand_5")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_othercommand_5)
        self.textEdit_othercommand_clustering = QtWidgets.QTextEdit(parent=self.frame_clustering)
        self.textEdit_othercommand_clustering.setObjectName("textEdit_othercommand_clustering")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_othercommand_clustering)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_clustering)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.radioButton_asv = QtWidgets.QRadioButton(parent=self.frame_clustering)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_asv.setFont(font)
        self.radioButton_asv.setChecked(True)
        self.radioButton_asv.setObjectName("radioButton_asv")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButton_asv)
        self.radioButton_otu = QtWidgets.QRadioButton(parent=self.frame_clustering)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_otu.setFont(font)
        self.radioButton_otu.setObjectName("radioButton_otu")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radioButton_otu)
        self.label_11 = QtWidgets.QLabel(parent=self.frame_clustering)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_clustering)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.lineEdit_min_seq_size_clustering = QtWidgets.QLineEdit(parent=self.frame_clustering)
        self.lineEdit_min_seq_size_clustering.setObjectName("lineEdit_min_seq_size_clustering")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_min_seq_size_clustering)
        self.comboBox_size_annotation_mode_clustering = QtWidgets.QComboBox(parent=self.frame_clustering)
        self.comboBox_size_annotation_mode_clustering.setObjectName("comboBox_size_annotation_mode_clustering")
        self.comboBox_size_annotation_mode_clustering.addItem("")
        self.comboBox_size_annotation_mode_clustering.addItem("")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_size_annotation_mode_clustering)
        self.verticalLayout_7.addWidget(self.frame_clustering)
        self.tabWidget.addTab(self.tab_clustering, "")
        self.tab_remove_chimeric = QtWidgets.QWidget()
        self.tab_remove_chimeric.setObjectName("tab_remove_chimeric")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_remove_chimeric)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_remove_chimera = QtWidgets.QFrame(parent=self.tab_remove_chimeric)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_remove_chimera.sizePolicy().hasHeightForWidth())
        self.frame_remove_chimera.setSizePolicy(sizePolicy)
        self.frame_remove_chimera.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_remove_chimera.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_remove_chimera.setObjectName("frame_remove_chimera")
        self.formLayout_7 = QtWidgets.QFormLayout(self.frame_remove_chimera)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setVerticalSpacing(15)
        self.formLayout_7.setObjectName("formLayout_7")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_remove_chimera)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_4)
        self.label_fastawidth_remove_chimeric = QtWidgets.QLabel(parent=self.frame_remove_chimera)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_fastawidth_remove_chimeric.setFont(font)
        self.label_fastawidth_remove_chimeric.setObjectName("label_fastawidth_remove_chimeric")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_fastawidth_remove_chimeric)
        self.lineEdit_seq_width_remove_chimeric = QtWidgets.QLineEdit(parent=self.frame_remove_chimera)
        self.lineEdit_seq_width_remove_chimeric.setObjectName("lineEdit_seq_width_remove_chimeric")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_seq_width_remove_chimeric)
        self.label_othercommand_6 = QtWidgets.QLabel(parent=self.frame_remove_chimera)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_othercommand_6.setFont(font)
        self.label_othercommand_6.setObjectName("label_othercommand_6")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_othercommand_6)
        self.textEdit_othercommand_remove_chimeric = QtWidgets.QTextEdit(parent=self.frame_remove_chimera)
        self.textEdit_othercommand_remove_chimeric.setObjectName("textEdit_othercommand_remove_chimeric")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_othercommand_remove_chimeric)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_remove_chimera)
        self.label_13.setObjectName("label_13")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.lineEdit_relabel_remove_chimeric = QtWidgets.QLineEdit(parent=self.frame_remove_chimera)
        self.lineEdit_relabel_remove_chimeric.setObjectName("lineEdit_relabel_remove_chimeric")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_relabel_remove_chimeric)
        self.verticalLayout_8.addWidget(self.frame_remove_chimera)
        self.tabWidget.addTab(self.tab_remove_chimeric, "")
        self.tab_taxonomic_assignment = QtWidgets.QWidget()
        self.tab_taxonomic_assignment.setObjectName("tab_taxonomic_assignment")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_taxonomic_assignment)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame = QtWidgets.QFrame(parent=self.tab_taxonomic_assignment)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_logo_blast = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo_blast.sizePolicy().hasHeightForWidth())
        self.label_logo_blast.setSizePolicy(sizePolicy)
        self.label_logo_blast.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_logo_blast.setText("")
        self.label_logo_blast.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "..", "..", "resources", "blast-150.png")))
        self.label_logo_blast.setScaledContents(True)
        self.label_logo_blast.setObjectName("label_logo_blast")
        self.horizontalLayout_9.addWidget(self.label_logo_blast)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_local_blast = QtWidgets.QRadioButton(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_local_blast.setFont(font)
        self.radioButton_local_blast.setChecked(True)
        self.radioButton_local_blast.setObjectName("radioButton_local_blast")
        self.horizontalLayout_7.addWidget(self.radioButton_local_blast)
        self.radioButton_olnine_blast = QtWidgets.QRadioButton(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_olnine_blast.setFont(font)
        self.radioButton_olnine_blast.setObjectName("radioButton_olnine_blast")
        self.horizontalLayout_7.addWidget(self.radioButton_olnine_blast)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.verticalLayout_9.addWidget(self.frame)
        self.frame_tax_assign_1 = QtWidgets.QFrame(parent=self.tab_taxonomic_assignment)
        self.frame_tax_assign_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_tax_assign_1.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_tax_assign_1.setObjectName("frame_tax_assign_1")
        self.formLayout_9 = QtWidgets.QFormLayout(self.frame_tax_assign_1)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setHorizontalSpacing(7)
        self.formLayout_9.setVerticalSpacing(10)
        self.formLayout_9.setObjectName("formLayout_9")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_tax_assign_1)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_6)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_tax_assign_1)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_DatabasePath = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_DatabasePath.setFont(font)
        self.pushButton_DatabasePath.setObjectName("pushButton_DatabasePath")
        self.horizontalLayout_5.addWidget(self.pushButton_DatabasePath)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frame_5)
        self.label_SampleName = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_SampleName.setFont(font)
        self.label_SampleName.setStyleSheet("")
        self.label_SampleName.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_SampleName.setObjectName("label_SampleName")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_SampleName)
        self.lineEdit_sample_name_blast = QtWidgets.QLineEdit(parent=self.frame_tax_assign_1)
        self.lineEdit_sample_name_blast.setObjectName("lineEdit_sample_name_blast")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_sample_name_blast)
        self.label_database = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_database.setFont(font)
        self.label_database.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_database.setObjectName("label_database")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_database)
        self.comboBox_database_type = QtWidgets.QComboBox(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_database_type.setFont(font)
        self.comboBox_database_type.setObjectName("comboBox_database_type")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.comboBox_database_type.addItem("")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_database_type)
        self.label_blastType = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_blastType.setFont(font)
        self.label_blastType.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_blastType.setObjectName("label_blastType")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_blastType)
        self.comboBox_blastType = QtWidgets.QComboBox(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_blastType.setFont(font)
        self.comboBox_blastType.setObjectName("comboBox_blastType")
        self.comboBox_blastType.addItem("")
        self.comboBox_blastType.addItem("")
        self.comboBox_blastType.addItem("")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_blastType)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.lineEdit_Percentage_identity = QtWidgets.QLineEdit(parent=self.frame_tax_assign_1)
        self.lineEdit_Percentage_identity.setObjectName("lineEdit_Percentage_identity")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_Percentage_identity)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.lineEdit_max_target_seq_blast = QtWidgets.QLineEdit(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_max_target_seq_blast.setFont(font)
        self.lineEdit_max_target_seq_blast.setObjectName("lineEdit_max_target_seq_blast")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_max_target_seq_blast)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_tax_assign_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_9.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_10)
        self.lineEdit_cpu_threads_blast = QtWidgets.QLineEdit(parent=self.frame_tax_assign_1)
        self.lineEdit_cpu_threads_blast.setObjectName("lineEdit_cpu_threads_blast")
        self.formLayout_9.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_cpu_threads_blast)
        self.verticalLayout_9.addWidget(self.frame_tax_assign_1)
        self.frame__tax_assign_3 = QtWidgets.QFrame(parent=self.tab_taxonomic_assignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame__tax_assign_3.sizePolicy().hasHeightForWidth())
        self.frame__tax_assign_3.setSizePolicy(sizePolicy)
        self.frame__tax_assign_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame__tax_assign_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame__tax_assign_3.setObjectName("frame__tax_assign_3")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame__tax_assign_3)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setHorizontalSpacing(0)
        self.formLayout_8.setVerticalSpacing(10)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_ProgressBar = QtWidgets.QLabel(parent=self.frame__tax_assign_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_ProgressBar.setFont(font)
        self.label_ProgressBar.setObjectName("label_ProgressBar")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_ProgressBar)
        self.progressBar_blast = QtWidgets.QProgressBar(parent=self.frame__tax_assign_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.progressBar_blast.setFont(font)
        self.progressBar_blast.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"    color: #333;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                      stop: 0 #4CAF50, stop: 1 #8BC34A);\n"
"    border-radius: 8px;\n"
"    margin: 1px;\n"
"}")
        self.progressBar_blast.setProperty("value", 0)
        self.progressBar_blast.setInvertedAppearance(False)
        self.progressBar_blast.setObjectName("progressBar_blast")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.progressBar_blast)
        self.verticalLayout_9.addWidget(self.frame__tax_assign_3)
        self.tabWidget.addTab(self.tab_taxonomic_assignment, "")
        self.horizontalLayout_14.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_9 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(20, 0, 0, 5)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(parent=self.frame_9)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(20, 1, 1, 1)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_adapter_trimming = QtWidgets.QCheckBox(parent=self.frame_7)
        self.checkBox_adapter_trimming.setChecked(True)
        self.checkBox_adapter_trimming.setObjectName("checkBox_adapter_trimming")
        self.horizontalLayout_10.addWidget(self.checkBox_adapter_trimming)
        self.checkBox_primer_trimming = QtWidgets.QCheckBox(parent=self.frame_7)
        self.checkBox_primer_trimming.setChecked(True)
        self.checkBox_primer_trimming.setObjectName("checkBox_primer_trimming")
        self.horizontalLayout_10.addWidget(self.checkBox_primer_trimming)
        self.checkBox_merging = QtWidgets.QCheckBox(parent=self.frame_7)
        self.checkBox_merging.setChecked(True)
        self.checkBox_merging.setObjectName("checkBox_merging")
        self.horizontalLayout_10.addWidget(self.checkBox_merging)
        self.checkBox_quality_filtering = QtWidgets.QCheckBox(parent=self.frame_7)
        self.checkBox_quality_filtering.setChecked(True)
        self.checkBox_quality_filtering.setObjectName("checkBox_quality_filtering")
        self.horizontalLayout_10.addWidget(self.checkBox_quality_filtering)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(20, 1, 1, 1)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_identify_unique_seq = QtWidgets.QCheckBox(parent=self.frame_8)
        self.checkBox_identify_unique_seq.setChecked(True)
        self.checkBox_identify_unique_seq.setObjectName("checkBox_identify_unique_seq")
        self.horizontalLayout_8.addWidget(self.checkBox_identify_unique_seq)
        self.checkBox_clustering = QtWidgets.QCheckBox(parent=self.frame_8)
        self.checkBox_clustering.setChecked(True)
        self.checkBox_clustering.setObjectName("checkBox_clustering")
        self.horizontalLayout_8.addWidget(self.checkBox_clustering)
        self.checkBox_remove_chimeric = QtWidgets.QCheckBox(parent=self.frame_8)
        self.checkBox_remove_chimeric.setChecked(True)
        self.checkBox_remove_chimeric.setObjectName("checkBox_remove_chimeric")
        self.horizontalLayout_8.addWidget(self.checkBox_remove_chimeric)
        self.checkBox_taxonomic_assignment = QtWidgets.QCheckBox(parent=self.frame_8)
        self.checkBox_taxonomic_assignment.setChecked(True)
        self.checkBox_taxonomic_assignment.setObjectName("checkBox_taxonomic_assignment")
        self.horizontalLayout_8.addWidget(self.checkBox_taxonomic_assignment)
        self.verticalLayout.addWidget(self.frame_8)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_reset = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_reset.setStyleSheet("QPushButton {\n"
"    background-color: #0078D7; \n"
"    color: white; \n"
"    border: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px 20px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005A9E; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003764; \n"
"}")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_reset)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_run = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_run.setStyleSheet("QPushButton {\n"
"    background-color: #0078D7; \n"
"    color: white; \n"
"    border: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px 20px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005A9E; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003764; \n"
"}")
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_2.addWidget(self.pushButton_run)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.widget)
        AllinOne.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AllinOne)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        AllinOne.setMenuBar(self.menubar)
        self.actionLoad_Forward_File = QtGui.QAction(parent=AllinOne)
        self.actionLoad_Forward_File.setObjectName("actionLoad_Forward_File")
        self.actionLoad_Reverse_File = QtGui.QAction(parent=AllinOne)
        self.actionLoad_Reverse_File.setObjectName("actionLoad_Reverse_File")
        self.menuFile.addAction(self.actionLoad_Forward_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Reverse_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(AllinOne)
        self.tabWidget.setCurrentIndex(0)
        self.radioButton_asv.toggled['bool'].connect(self.lineEdit_min_seq_size_clustering.setEnabled) # type: ignore
        self.radioButton_asv.toggled['bool'].connect(self.comboBox_size_annotation_mode_clustering.setEnabled) # type: ignore
        self.radioButton_local_blast.toggled['bool'].connect(self.pushButton_DatabasePath.setEnabled) # type: ignore
        self.radioButton_olnine_blast.toggled['bool'].connect(self.progressBar_blast.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AllinOne)

    def retranslateUi(self, AllinOne):
        _translate = QtCore.QCoreApplication.translate
        AllinOne.setWindowTitle(_translate("AllinOne", "Run Full Pipeline"))
        self.groupBox.setTitle(_translate("AllinOne", "Parameters:"))
        self.label_forward.setToolTip(_translate("AllinOne", "Forward reads"))
        self.label_forward.setText(_translate("AllinOne", "Forward Adapter:"))
        self.lineEdit_forward_trim_adapter.setPlaceholderText(_translate("AllinOne", "Forward adapter sequences"))
        self.label_reverse.setToolTip(_translate("AllinOne", "Reverse reads"))
        self.label_reverse.setText(_translate("AllinOne", "Reverse Adapter:"))
        self.lineEdit_reverse_trim_adapter.setPlaceholderText(_translate("AllinOne", "Reverse adapter sequences"))
        self.label_min.setToolTip(_translate("AllinOne", "minimum length: Discard processed reads that are shorter than LENGTH"))
        self.label_min.setText(_translate("AllinOne", "Min Length:"))
        self.lineEdit_min__trim_adapter.setPlaceholderText(_translate("AllinOne", "Min length"))
        self.label_quality.setToolTip(_translate("AllinOne", "Quality trimming: this parameter can be used to trim low-quality ends from reads"))
        self.label_quality.setText(_translate("AllinOne", "Quality cutoff:"))
        self.lineEdit_quality_trim_adapter.setPlaceholderText(_translate("AllinOne", "Quality cutoff"))
        self.label_max.setToolTip(_translate("AllinOne", "maximum number of N bases: Discard reads containing more than COUNT N bases"))
        self.label_max.setText(_translate("AllinOne", "Max-n:"))
        self.lineEdit_max_trim_adapter.setPlaceholderText(_translate("AllinOne", "Max_n"))
        self.label_overlap.setToolTip(_translate("AllinOne", "Minimum overlap. reducing random matches (default: 3)"))
        self.label_overlap.setText(_translate("AllinOne", "Overlap:"))
        self.lineEdit_overlap_trim_adapter.setPlaceholderText(_translate("AllinOne", "3"))
        self.label_errorRate.setToolTip(_translate("AllinOne", "Maximum error rate (default: 0.1)"))
        self.label_errorRate.setText(_translate("AllinOne", "Error rate:"))
        self.lineEdit_error_trim_adapter.setPlaceholderText(_translate("AllinOne", "0.1"))
        self.label_discarduntrim.setToolTip(_translate("AllinOne", "Discard reads in which no adapter was found"))
        self.label_discarduntrim.setText(_translate("AllinOne", "Discard untrimmed:"))
        self.radioButton_yes_trim_adapter.setText(_translate("AllinOne", "Yes"))
        self.radioButton_no_trim_adapter.setText(_translate("AllinOne", "No"))
        self.label_othercommand.setToolTip(_translate("AllinOne", "You can include additional parameters. For more details, refer to the Cutadapt documentation available at: https://cutadapt.readthedocs.io/en/stable/index.html"))
        self.label_othercommand.setText(_translate("AllinOne", "Other commands:"))
        self.textEdit_othercommand_trim_adapter.setPlaceholderText(_translate("AllinOne", "You can include additional parameters. For more details, refer to the Cutadapt documentation available at: https://cutadapt.readthedocs.io/en/stable/index.html"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adapter_trimmig), _translate("AllinOne", "Adapter Trimming"))
        self.label_forward_2.setToolTip(_translate("AllinOne", "Forward reads"))
        self.label_forward_2.setText(_translate("AllinOne", "Forward Primer:      "))
        self.lineEdit_forward_trim_primer.setPlaceholderText(_translate("AllinOne", "Forward primer sequences"))
        self.label_reverse_2.setToolTip(_translate("AllinOne", "Reverse reads"))
        self.label_reverse_2.setText(_translate("AllinOne", "Reverse Primer:      "))
        self.lineEdit_reverse_trim_primer.setPlaceholderText(_translate("AllinOne", "Reverse primer sequences"))
        self.label_min_2.setToolTip(_translate("AllinOne", "minimum length: Discard processed reads that are shorter than LENGTH"))
        self.label_min_2.setText(_translate("AllinOne", "Min Length:            "))
        self.lineEdit_min__trim_primer.setPlaceholderText(_translate("AllinOne", "Min length"))
        self.label_quality_2.setToolTip(_translate("AllinOne", "Quality trimming: this parameter can be used to trim low-quality ends from reads"))
        self.label_quality_2.setText(_translate("AllinOne", "Quality cutoff:         "))
        self.lineEdit_quality_trim_primer.setPlaceholderText(_translate("AllinOne", "Quality cutoff"))
        self.label_max_2.setToolTip(_translate("AllinOne", "maximum number of N bases: Discard reads containing more than COUNT N bases"))
        self.label_max_2.setText(_translate("AllinOne", "Max-n:                   "))
        self.lineEdit_max_trim_primer.setPlaceholderText(_translate("AllinOne", "Max_n"))
        self.label_overlap_2.setToolTip(_translate("AllinOne", "Minimum overlap. reducing random matches (default: 3)"))
        self.label_overlap_2.setText(_translate("AllinOne", "Overlap:                 "))
        self.lineEdit_overlap_trim_primer.setPlaceholderText(_translate("AllinOne", "3"))
        self.label_errorRate_2.setToolTip(_translate("AllinOne", "Maximum error rate (default: 0.1)"))
        self.label_errorRate_2.setText(_translate("AllinOne", "Error rate:              "))
        self.lineEdit_error_trim_primer.setPlaceholderText(_translate("AllinOne", "0.1"))
        self.label_discarduntrim_2.setToolTip(_translate("AllinOne", "Discard reads in which no adapter was found"))
        self.label_discarduntrim_2.setText(_translate("AllinOne", "Discard untrimmed:"))
        self.radioButton_yes_trim_primer.setText(_translate("AllinOne", "Yes"))
        self.radioButton_no_trim_primer.setText(_translate("AllinOne", "No"))
        self.label_othercommand_2.setToolTip(_translate("AllinOne", "You can include additional parameters. For more details, refer to the Cutadapt documentation available at: https://cutadapt.readthedocs.io/en/stable/index.html"))
        self.label_othercommand_2.setText(_translate("AllinOne", "Other commands:   "))
        self.textEdit_othercommand_trim_primer.setPlaceholderText(_translate("AllinOne", "You can include additional parameters. For more details, refer to the Cutadapt documentation available at: https://cutadapt.readthedocs.io/en/stable/index.html"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_primer_trimming), _translate("AllinOne", "Primer Trimming"))
        self.label_3.setText(_translate("AllinOne", "Minimum Overlap Length:"))
        self.lineEdit_min_overlap_merging.setPlaceholderText(_translate("AllinOne", "20"))
        self.label_4.setText(_translate("AllinOne", "Maximum Overlap Mismatches:"))
        self.lineEdit_max_overlap_mismatch_merging.setPlaceholderText(_translate("AllinOne", "5"))
        self.label_5.setText(_translate("AllinOne", "Other commands:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_merging), _translate("AllinOne", "Merging"))
        self.label_maxee.setToolTip(_translate("AllinOne", "Discard sequences with expected error above specified value (from 0.0 to infinity)"))
        self.label_maxee.setText(_translate("AllinOne", "Maximum expected error:"))
        self.label_max_length.setToolTip(_translate("AllinOne", "discard sequences with\n"
"more than the specified number of bases"))
        self.label_max_length.setText(_translate("AllinOne", "Maximum length:"))
        self.label_min_length.setToolTip(_translate("AllinOne", " discard input sequences\n"
"with less than the specified number of bases (default 1)"))
        self.label_min_length.setText(_translate("AllinOne", "Minimum length:"))
        self.label_2.setText(_translate("AllinOne", "Maximum N Bases:"))
        self.label_min_quality_score.setText(_translate("AllinOne", "Minimum Quality Score:"))
        self.label_relabel.setToolTip(_translate("AllinOne", "Relabel sequences using the prefix string"))
        self.label_relabel.setText(_translate("AllinOne", "Relabel sequences:"))
        self.label_othercommand_3.setToolTip(_translate("AllinOne", "You can add additional parameters"))
        self.label_othercommand_3.setText(_translate("AllinOne", "Other commands:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_quality_filtering), _translate("AllinOne", "Quality Filtering"))
        self.label_relabel_2.setToolTip(_translate("AllinOne", "Relabel sequences using the prefix string"))
        self.label_relabel_2.setText(_translate("AllinOne", "Relabel sequences:"))
        self.label_othercommand_4.setToolTip(_translate("AllinOne", "You can add additional parameters"))
        self.label_othercommand_4.setText(_translate("AllinOne", "Other commands:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_identify_unique), _translate("AllinOne", "Identifying Unique Seq"))
        self.label_othercommand_5.setText(_translate("AllinOne", "Other commands:"))
        self.label_6.setText(_translate("AllinOne", "Clustering type:"))
        self.radioButton_asv.setText(_translate("AllinOne", "ASV"))
        self.radioButton_otu.setText(_translate("AllinOne", "OTU"))
        self.label_11.setText(_translate("AllinOne", "Minimum Sequence Size:"))
        self.label_12.setText(_translate("AllinOne", "Size Annotation Mode:"))
        self.lineEdit_min_seq_size_clustering.setText(_translate("AllinOne", "8"))
        self.comboBox_size_annotation_mode_clustering.setItemText(0, _translate("AllinOne", "Size_out"))
        self.comboBox_size_annotation_mode_clustering.setItemText(1, _translate("AllinOne", "Size_out and Size_in"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_clustering), _translate("AllinOne", "Clustering"))
        self.label_fastawidth_remove_chimeric.setText(_translate("AllinOne", "Sequence width:"))
        self.label_othercommand_6.setText(_translate("AllinOne", "Other commands:"))
        self.label_13.setText(_translate("AllinOne", "Relabel sequences:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_remove_chimeric), _translate("AllinOne", "Remove Chimeric"))
        self.radioButton_local_blast.setText(_translate("AllinOne", "Local Blast"))
        self.radioButton_olnine_blast.setText(_translate("AllinOne", "Online Blast"))
        self.label_9.setText(_translate("AllinOne", "Database Path:"))
        self.pushButton_DatabasePath.setText(_translate("AllinOne", "Browse..."))
        self.label_SampleName.setText(_translate("AllinOne", "<span style=\"color: black;\">Sample Name: </span><span style=\"color: red;\">*</span>"))
        self.label_database.setText(_translate("AllinOne", "<span style=\"color: black;\">Database: </span><span style=\"color: red;\">*</span>"))
        self.comboBox_database_type.setItemText(0, _translate("AllinOne", "Core nucleotide database (core_nt)"))
        self.comboBox_database_type.setItemText(1, _translate("AllinOne", "RefSeq Select RNA sequences (refseq_select)"))
        self.comboBox_database_type.setItemText(2, _translate("AllinOne", "Reference RNA sequences (refseq_rna)"))
        self.comboBox_database_type.setItemText(3, _translate("AllinOne", "RefSeq Reference genomes (refseq_reference_genomes)"))
        self.comboBox_database_type.setItemText(4, _translate("AllinOne", "RefSeq Genome Database (refseq_genomes)"))
        self.comboBox_database_type.setItemText(5, _translate("AllinOne", "Nucleotide collection (nr/nt)"))
        self.comboBox_database_type.setItemText(6, _translate("AllinOne", "Whole-genome shotgun contigs (wgs)"))
        self.comboBox_database_type.setItemText(7, _translate("AllinOne", "Expressed sequence tags (est)"))
        self.comboBox_database_type.setItemText(8, _translate("AllinOne", "Sequence Read Archive (SRA)"))
        self.comboBox_database_type.setItemText(9, _translate("AllinOne", "Transcriptome Shotgun Assembly (TSA)"))
        self.comboBox_database_type.setItemText(10, _translate("AllinOne", "Targeted Loci (TLS)"))
        self.comboBox_database_type.setItemText(11, _translate("AllinOne", "High throughput genomic sequences (HTGS)"))
        self.comboBox_database_type.setItemText(12, _translate("AllinOne", "Patent sequences (pat)"))
        self.comboBox_database_type.setItemText(13, _translate("AllinOne", "PDB nucleotide database (pdb)"))
        self.comboBox_database_type.setItemText(14, _translate("AllinOne", "Human RefSeqGene sequences (RefSeq_Gene)"))
        self.comboBox_database_type.setItemText(15, _translate("AllinOne", "Genomic survey sequences (gss)"))
        self.comboBox_database_type.setItemText(16, _translate("AllinOne", "Sequence tagged sites (dbsts)"))
        self.label_blastType.setText(_translate("AllinOne", "<span style=\"color: black;\">Optimize for: </span><span style=\"color: red;\">*</span>"))
        self.comboBox_blastType.setItemText(0, _translate("AllinOne", "Highly similar sequences (megablast)"))
        self.comboBox_blastType.setItemText(1, _translate("AllinOne", "More dissimilar sequences (discontiguous megablast)"))
        self.comboBox_blastType.setItemText(2, _translate("AllinOne", "Somewhat similar sequences (blastn)"))
        self.label_8.setText(_translate("AllinOne", "Percentage Identity:"))
        self.lineEdit_Percentage_identity.setPlaceholderText(_translate("AllinOne", "97"))
        self.label_7.setText(_translate("AllinOne", "Max Target Seqs:"))
        self.lineEdit_max_target_seq_blast.setPlaceholderText(_translate("AllinOne", "30"))
        self.label_10.setText(_translate("AllinOne", "CPU Threads:"))
        self.lineEdit_cpu_threads_blast.setPlaceholderText(_translate("AllinOne", "12"))
        self.label_ProgressBar.setText(_translate("AllinOne", "Retrieve data from Blast Online:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_taxonomic_assignment), _translate("AllinOne", "Taxonomic Assignment"))
        self.label.setText(_translate("AllinOne", "Steps to Run:"))
        self.checkBox_adapter_trimming.setText(_translate("AllinOne", "Adapter Trimming"))
        self.checkBox_primer_trimming.setText(_translate("AllinOne", "Primer Trimming"))
        self.checkBox_merging.setText(_translate("AllinOne", "Merging"))
        self.checkBox_quality_filtering.setText(_translate("AllinOne", "Quality Filtering"))
        self.checkBox_identify_unique_seq.setText(_translate("AllinOne", "Identifying Unique Seq"))
        self.checkBox_clustering.setText(_translate("AllinOne", "Clustering"))
        self.checkBox_remove_chimeric.setText(_translate("AllinOne", "Remove Chimeric"))
        self.checkBox_taxonomic_assignment.setText(_translate("AllinOne", "Taxonomic Assignment"))
        self.pushButton_reset.setText(_translate("AllinOne", "Reset"))
        self.pushButton_run.setText(_translate("AllinOne", "Run"))
        self.menuFile.setTitle(_translate("AllinOne", "File"))
        self.actionLoad_Forward_File.setText(_translate("AllinOne", "Load Forward File"))
        self.actionLoad_Reverse_File.setText(_translate("AllinOne", "Load Reverse File"))
