# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(680, 273)
        self.centralwidget = QtWidgets.QWidget(parent=Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_vsearch = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_vsearch.setObjectName("pushButton_vsearch")
        self.horizontalLayout.addWidget(self.pushButton_vsearch)
        self.lineEdit_vsearch = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_vsearch.setObjectName("lineEdit_vsearch")
        self.horizontalLayout.addWidget(self.lineEdit_vsearch)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pushButton_blast = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_blast.setObjectName("pushButton_blast")
        self.horizontalLayout_3.addWidget(self.pushButton_blast)
        self.lineEdit_blast = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_blast.setObjectName("lineEdit_blast")
        self.horizontalLayout_3.addWidget(self.lineEdit_blast)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        Settings.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Settings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 26))
        self.menubar.setObjectName("menubar")
        Settings.setMenuBar(self.menubar)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.groupBox.setTitle(_translate("Settings", "Tools:"))
        self.label.setText(_translate("Settings", "VSEARCH Path:"))
        self.pushButton_vsearch.setText(_translate("Settings", "Browse..."))
        self.label_3.setText(_translate("Settings", "BLAST Path:    "))
        self.pushButton_blast.setText(_translate("Settings", "Browse..."))
