# Form implementation generated from reading ui file 'Blast_Database.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_blastdb(object):
    def setupUi(self, blastdb):
        blastdb.setObjectName("blastdb")
        blastdb.resize(662, 434)
        self.centralwidget = QtWidgets.QWidget(parent=blastdb)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_database_path = QtWidgets.QLabel(parent=self.frame)
        self.label_database_path.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_database_path.setObjectName("label_database_path")
        self.gridLayout.addWidget(self.label_database_path, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_DB_Names = QtWidgets.QComboBox(parent=self.frame_2)
        self.comboBox_DB_Names.setObjectName("comboBox_DB_Names")
        self.horizontalLayout.addWidget(self.comboBox_DB_Names)
        spacerItem = QtWidgets.QSpacerItem(395, 14, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_DatabasePath = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_DatabasePath.setObjectName("pushButton_DatabasePath")
        self.horizontalLayout_3.addWidget(self.pushButton_DatabasePath)
        spacerItem1 = QtWidgets.QSpacerItem(432, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 614, 270))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.frame)
        blastdb.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=blastdb)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 26))
        self.menubar.setObjectName("menubar")
        blastdb.setMenuBar(self.menubar)

        self.retranslateUi(blastdb)
        QtCore.QMetaObject.connectSlotsByName(blastdb)

    def retranslateUi(self, blastdb):
        _translate = QtCore.QCoreApplication.translate
        blastdb.setWindowTitle(_translate("blastdb", "Blast Database Management"))
        self.label.setText(_translate("blastdb", "<html><head/><body><p><span style=\" color:#000000;\">Database Name: </span><span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.label_database_path.setText(_translate("blastdb", "<span style=\"color: black;\">Database Path: </span><span style=\"color: red;\">*</span>"))
        self.pushButton_DatabasePath.setText(_translate("blastdb", "Browse..."))
