# Form implementation generated from reading ui file 'Samples_management.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Samples_management(object):
    def setupUi(self, Samples_management):
        Samples_management.setObjectName("Samples_management")
        Samples_management.resize(523, 410)
        self.centralwidget = QtWidgets.QWidget(parent=Samples_management)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("QLabel {\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    margin-bottom: 10px;\n"
"}")
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 475, 293))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame)
        Samples_management.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Samples_management)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        Samples_management.setMenuBar(self.menubar)
        self.actionLoad_Database = QtGui.QAction(parent=Samples_management)
        self.actionLoad_Database.setObjectName("actionLoad_Database")
        self.menuFile.addAction(self.actionLoad_Database)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Samples_management)
        QtCore.QMetaObject.connectSlotsByName(Samples_management)

    def retranslateUi(self, Samples_management):
        _translate = QtCore.QCoreApplication.translate
        Samples_management.setWindowTitle(_translate("Samples_management", "Sample Repository"))
        self.label.setText(_translate("Samples_management", "<html><head/><body><p>You can edit the sample name or delete it.</p></body></html>"))
        self.menuFile.setTitle(_translate("Samples_management", "File"))
        self.actionLoad_Database.setText(_translate("Samples_management", "Load Database"))
