# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(508, 312)
        self.centralwidget = QtWidgets.QWidget(parent=About)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 501, 281))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.frame)
        About.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=About)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 26))
        self.menubar.setObjectName("menubar")
        About.setMenuBar(self.menubar)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About MetaBioDetect"))
        self.textBrowser.setHtml(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">MetaBioDetect</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MetaBioDetect is an open-source graphical software designed for DNA metabarcoding analysis and amplicon sequencing data processing. The platform integrates widely used bioinformatics tools including </span><span style=\" font-size:9pt; font-weight:600;\">VSEARCH</span><span style=\" font-size:9pt;\">, </span><span style=\" font-size:9pt; font-weight:600;\">Cutadapt</span><span style=\" font-size:9pt;\">, and </span><span style=\" font-size:9pt; font-weight:600;\">BLAST</span><span style=\" font-size:9pt;\"> into an intuitive graphical user interface (GUI), allowing researchers to perform complex metabarcoding analyses without requiring advanced command-line expertise.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">The software provides a complete workflow for sequence preprocessing, clustering, and taxonomy assignment. Users can perform adapter and primer trimming, read merging, quality filtering, dereplication, clustering into </span><span style=\" font-size:9pt; font-weight:600;\">ASVs or OTUs</span><span style=\" font-size:9pt;\">, chimera detection, and taxonomic identification using online BLAST, local databases, or custom reference datasets.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MetaBioDetect was developed in </span><span style=\" font-size:9pt; font-weight:600;\">Python</span><span style=\" font-size:9pt;\"> using the </span><span style=\" font-size:9pt; font-weight:600;\">PyQt</span><span style=\" font-size:9pt;\"> framework and is designed to run across multiple operating systems. The software aims to make metabarcoding analysis more accessible, reproducible, and efficient for applications in biodiversity monitoring, environmental research, and food authenticity testing.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Developers:</span><span style=\" font-size:9pt;\"><br />Sajad Falsafi Zadeh,<br />Zahra Karimi</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">MetaBioDetect is open-source software released under the MIT License.</span></p></body></html>"))